spring:
  application:
   name: doctor-anywhere-app
  
  mvc:
   view:
     prefix: /WEB-INF/jsp/    
     suffix: .jsp
     
  jpa:
   show-sql: true  
   hibernate:
    ddl-auto: none   
    
  h2:
   console:
    enabled: true   
    
  datasource:
   url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
   username: sa
   password: sa
   driverClassName: org.h2.Driver
     
server:
 port: 8020     
 
 
app:
 exceptionDetailsMap:
    MSP_1000_addItems: Error occured during the processing of Add Dishes information, please try again.

 logger:
   path: D:/Self_Log