------------------------ PATIENT ----------------------------
DROP TABLE IF EXISTS PATIENT;
DROP SEQUENCE IF EXISTS PATIENT_SEQ;

CREATE SEQUENCE PATIENT_SEQ;

CREATE TABLE PATIENT (
   PATIENT_ID INT NOT NULL, 
   PATIENT_FIRST_NAME VARCHAR(50) NOT NULL, 
   PATIENT_LAST_NAME VARCHAR(20) NOT NULL, 
   CONTACT_NUMBER VARCHAR(20) NOT NULL, 
   ACTIVE_FLAG VARCHAR(20) NOT NULL,
   MODIFIED_TS TIMESTAMP (6),
   CREATED_TS TIMESTAMP (6)
);

ALTER TABLE PATIENT ADD PRIMARY KEY (PATIENT_ID);

--------------Address Table---------------------------
DROP TABLE IF EXISTS ADDRESS;

DROP SEQUENCE IF EXISTS ADDRESS_SEQ;

CREATE SEQUENCE ADDRESS_SEQ;

CREATE TABLE ADDRESS (
   ADDRESS_ID INT NOT NULL, 
   PATIENT_ID INT NOT NULL,
   ADDRESS_LINE_1 VARCHAR(100), 
   ADDRESS_LINE_2 VARCHAR(100), 
   CITY VARCHAR(20) NOT NULL, 
   COUNTRY VARCHAR(20) NOT NULL, 
   POSTAL_CODE VARCHAR(20) NOT NULL, 
   ACTIVE_FLAG VARCHAR(20) NOT NULL,
   MODIFIED_TS TIMESTAMP (6),
   CREATED_TS TIMESTAMP (6)
);

ALTER TABLE ADDRESS ADD PRIMARY KEY (ADDRESS_ID);
ALTER TABLE ADDRESS ADD CONSTRAINT FK_PATIENT_IDX_PK_ADDRESS FOREIGN KEY ( PATIENT_ID ) REFERENCES PATIENT( PATIENT_ID );

INSERT INTO PATIENT VALUES (9900, 'Dampuru', 'Vinod', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9901, 'Nalubolu', 'Sindhuja', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9902, 'Dampuru1', 'Vinod', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9903, 'Nalubolu1', 'Sindhuja', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9904, 'Dampuru2', 'Vinod', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9905, 'Nalubolu2', 'Sindhuja', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9906, 'Dampuru3', 'Vinod', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9907, 'Nalubolu3', 'Sindhuja', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9908, 'Dampuru4', 'Vinod', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9909, 'Nalubolu4', 'Sindhuja', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9910, 'Dampuru5', 'Vinod', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9911, 'Nalubolu5', 'Sindhuja', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9912, 'Dampuru6', 'Vinod', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9913, 'Nalubolu6', 'Sindhuja', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9914, 'Dampuru7', 'Vinod', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9915, 'Nalubolu7', 'Sindhuja', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9916, 'Dampuru8', 'Vinod', '098765543', 'Y', SYSDATE, SYSDATE);
INSERT INTO PATIENT VALUES (9917, 'Nalubolu8', 'Sindhuja', '098765543', 'Y', SYSDATE, SYSDATE);

INSERT INTO ADDRESS VALUES (9900, 9900, 'Block xx', '#07-xxx', 'Singapore', 'Singapore', '100792', 'Y', SYSDATE, SYSDATE);
INSERT INTO ADDRESS VALUES (9901, 9901, 'Block xx', '#07-xxx', 'Singapore', 'Singapore', '100213', 'Y', SYSDATE, SYSDATE);